### PR TITLE
feat: add `user:write:chat` scope

### PR DESCRIPTION
**Pull request by Nerixyz**
This one isn't in the docs yet, but needed for sending a message. Depends on https://github.com/twitch-rs/twitch_oauth2/pull/138.

### CODE REVIEW

**Comment by Emilgardis** [comment]
We could do a immediate release also with this, just need to update the changelog, commit, then [`cargo release patch`](https://github.com/crate-ci/cargo-release), push

**Comment by Nerixyz** [comment]
I updated the changelog, but I can't commit to main, so you'd need to do that.

**Comment by Emilgardis** [comment]
You dont need to commit to main, the ci does the release on merges that bump the version in Cargo.toml :D 

https://github.com/twitch-rs/twitch_oauth2/blob/ff18d8e109e5ded004eea4663faba92c84a4a1aa/xtask/src/main.rs#L32

**Comment by Nerixyz** [comment]
Ah, this should be correct now.

**Review by Emilgardis — APPROVED** [review]
lgtm!

**Pull request merged**
