### PR TITLE
Remove unused generic in from_existing.

### PR DESCRIPTION
**Pull request by Ethiraric**

### CODE REVIEW

**Review by Nerixyz — APPROVED** [review]
Technically, this would require a minor bump to 0.14.

It wasn't caught in CI/by clippy, because we don't have [`avoid-breaking-exported-api`](https://doc.rust-lang.org/clippy/lint_configuration.html#avoid-breaking-exported-api) disabled in a `clippy.toml`.

The only other warning `avoid-breaking-exported-api` introduces is

```text
warning: methods with the following characteristics: (`to_*` and `self` type is not `Copy`) usually take `self` by reference
   --> src\scopes.rs:229:31
    |
229 |     pub const fn to_validator(self) -> Validator { Validator::scope(self) }
    |                               ^^^^
    |
    = help: consider choosing a less ambiguous name
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
```

**Comment by Emilgardis** [comment]
Id say lets do this, after a release to get the new scopes in.

**Comment by Emilgardis** [comment]
I think its possible to workaround this with `from_existing::<(), reqwest::Client>`. Do t have access to my computer right now so cant double-check

**Comment by Ethiraric** [comment]
That would work indeed. Was that a generic which was used then dropped? I have no idea what significance it has.

**Comment by Emilgardis** [comment]
I missed it in #71 https://github.com/twitch-rs/twitch_oauth2/commit/0dd50889dba090ac8e9c5b2f7ac1e993e4a9b7c3#diff-5978d330720a98082be35f9d1144eef34ca2dfc4b055abe01328003e6b35d766R113

It used to be exactly what Client::Error is, but I realized it could be factored away

**Pull request merged**
